### ISSUE TITLE
Improvements to Arctos Tools Directory

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#5698]
@DerekSikes has suggested the following:

 - [ ] For consistency call this "Arctos Tools", including in the menu. https://github.com/ArctosDB/arctos/issues/5536#issuecomment-1440682154 
![image](https://user-images.githubusercontent.com/5725767/220761296-f83c109f-b53e-46fe-9805-a9cddcdb9c2a.png)
 - [ ] Make the Tile Headers a larger font https://github.com/ArctosDB/arctos/issues/5536#issuecomment-1440715791 ![Screen Shot 2023-02-22 at 10 56 18 AM Feb 22, 23](https://user-images.githubusercontent.com/9099827/220744466-e0b30883-e440-4d37-9f90-6e1db1c2a50e.jpg)
 - [ ] why does the 'Search' drop down menu (upper left of header) have different links than the 'Search' box on the 'Manage' page?? shouldn't they have the same links? https://github.com/ArctosDB/arctos/issues/5536#issuecomment-1440710106
 - [ ] the link says 'Record Summary' but the tool says "Catalog Record Summary" - one thing should be called by one name. https://github.com/ArctosDB/arctos/issues/5536#issuecomment-1440710106

**Comment by campmlc** [comment]
I'm pretty partial to " Manage", as it is clear and simple and there is already too much not clear/not simple wording on many of the drop down menus ( Loan Search, for example why not Accession Search, and on separate line, Loan Search?)
 Currently, the manage tools are limited to operators to enter and manage data. Do any of the View permissions give Manage access? Will we ever want any tools in this drop-down to be publicly visible? If so, maybe Tools is ok, but I still prefer Manage.

**Comment by Jegelewicz** [comment]
A public user still has some access in "Manage" aka "Tools Directory"

![image](https://user-images.githubusercontent.com/5725767/220773572-e947a5d1-ac2d-4926-a1bd-206937b2f7fe.png)

**Comment by Jegelewicz** [comment]
> why not Accession Search, and on separate line, Loan Search?

because they are the same tool and I don't think we can add a tool to the menu twice (but I could be wrong).

**Comment by Jegelewicz** [comment]
> For consistency call this "Arctos Tools", including in the menu. 

No need to be redundant - just say "Tools"

But I don't really like that for some reason - and I am not sure "Manage" captures what is really there, which are "Tools" but right now, I don't have any better ideas.

**Comment by campmlc** [comment]
Have them direct to the same link. But I have to search for loans multiple
times a day, and each time I do a double take because I have to look under
Accessions to find them.

**Comment by campmlc** [comment]
If Loans has its own entry, I could look for loans under "L".

**Comment by Jegelewicz** [comment]
> why does the 'Search' drop down menu (upper left of header) have different links than the 'Search' box on the 'Manage' page?? shouldn't they have the same links?

Here is a summary of the two

Main Menu Search | Tools Search | Tools Match to Main Menu 
-- | -- | --
Browse Collections |   | Portals
Find Catalog Records | Agents | Catalog Records
Find Publications/Projects | **Arctos   Directory** | Publications & Projects
Taxonomy | **Browse Arctos Tables** | Taxonomy
Media/Documents | Catalog Records | Media/Documents
**Geography** | Code Tables |  
Locality | Get Something Random | Places
**Event** | Google Custom (BETA) |  
Explore Code Tables | Media/Documents | Code Tables
Google Site Search | Places | Google Custom (BETA)
Agents | Portals | Agents
**API** | Publications & Projects |  
Randomizer | Taxonomy | Get Something Random


I think changing the names of things in the Tools Directory to match the Search dropdown makes sense. BUT there are three terms in the main menu that are not represented in the Tools Directory (maybe they just haven't been added?) 
 - Geography
 - Event
 - API

and there are two in the Tools Directory Search that are not on the main menu
 - Arctos Directory (this is a weird circular link to the Tools Page - maybe we should remove it)
 - Browse Arctos Tables (suggest moving this to For Developers)

**Comment by Jegelewicz** [comment]
I don't know what the deal is but we have two ways of searching "locality?

Places - https://arctos.database.museum/place.cfm
Locality - https://arctos.database.museum/place.cfm?sch=locality

which seems super not helpful?

**Comment by campmlc** [comment]
I notice we also are inconsistent with the search terms. I would prefer losing the verb whenever possible, for example, under the Search menu, the first two terms should be Catalog Records and Collections, instead of adding the redundant Browse and Find. Fewer words to mentally parse, more clarity and consistency with other forms. When a verb is needed, it should come after the noun, so that similar categories of tools sort together.

**Comment by Jegelewicz** [comment]
>  would prefer losing the verb whenever possible, for example, under the Search menu, the first two terms should be Catalog Records and Collections, instead of adding the redundant Browse and Find. 

I like that!

**Comment by dustymc** [comment]
I think this is all duplicated elsewhere
