### ISSUE TITLE
Request - Change the order of dimensions on object tracking so they are always in the same order

### ISSUE THREAD

**Issue by falco-rk** [ArctosDB/arctos#8221]
Help us understand your request (check below):
- [ ] search or data request (help with SQL or provide the specific fields you are trying to retrieve for your collection)
- [ ] add a new Github user to the Arctos Users team
- [ ] a new barcode series
- [ ] a new term for data entry or management 
- [ ] a change or new report or label
- [ ] update to an Agent (split, merge, or other type of change)
- [ ] bulkload changes (to Agents, Identifiers, etc that are not already available as a bulkloading tool)
- [x] new feature or otherwise a good idea to make Arctos even better
- [ ] quarantine taxon name and suggested replacement (please supply links)
- [x] other

**Describe what you're trying to do** 
Dimension in object tracking bulkloaders are not in the same order and it drives me absolutely insane. For example, Bulk edit is height, length, width and Bulkload container is width, height, length. Can they be reordered so they are all in the same order? I don't even care what order they go in as long as they are the same everywhere.

@happiah-madson @dustymc @campmlc @mkoo

**Comment by falco-rk** [comment]
Also, depth and length are used interchangeably and that is confusing and terrible.

**Comment by campmlc** [comment]
Absolutely agree. @LitsaWoo  @DerekSikes @megulbranson

**Comment by dustymc** [comment]
>don't even care 

Well pick anyway and I'll add it to https://github.com/ArctosDB/dev/issues/39 (which has been ***almost*** on top of the pile forever...).

>interchangeably

Specifics please - if I didn't notice the first time I might not the second either...

FYI the table is:

```

                                    Table "core.container"
            Column             |            Type             | Collation | Nullable | Default 
-------------------------------+-----------------------------+-----------+----------+---------
 container_id                  | integer                     |           | not null | 
 parent_container_id           | integer                     |           | not null | 
 container_type                | character varying(30)       |           | not null | 
 label                         | character varying(255)      |           | not null | 
 description                   | character varying(255)      |           |          | 
 last_date                     | timestamp without time zone |           |          | 
 container_remarks             | character varying(4000)     |           |          | 
 barcode                       | character varying(50)       |           |          | 
 print_fg                      | smallint                    |           |          | 
 width                         | double precision            |           |          | 
 height                        | double precision            |           |          | 
 length                        | double precision            |           |          | 
 institution_acronym           | character varying(20)       |           | not null | 
 number_rows                   | integer                     |           |          | 
 number_columns                | integer                     |           |          | 
 orientation                   | character varying(25)       |           |          | 
 positions_hold_container_type | character varying(25)       |           |          | 
 last_update_tool              | character varying(255)      |           |          | 
 weight                        | numeric                     |           |          | 
 weight_units                  | character varying           |           |          | 
 weight_capacity               | numeric                     |           |          | 
 weight_capacity_units         | character varying           |           |          | 
```

**Comment by falco-rk** [comment]
>interchangeably

Most places say length rather than depth but in if you click into container details, dimensions are displayed as W x H x D: 

![Screenshot 2024-10-23 at 1 32 58 PM](https://github.com/user-attachments/assets/7f77413f-98b5-4cd1-ac08-ffae82898624)

>pick anyway

length, width, height

**Comment by dustymc** [comment]
Thanks, I updated https://github.com/ArctosDB/dev/issues/39, I think we're done here, tentatively closing.
