### ISSUE TITLE
Request - removal of a object tracking tool

### ISSUE THREAD

**Issue by happiah-madson** [ArctosDB/arctos#8230]
Help us understand your request (check below):
- [ ] search or data request (help with SQL or provide the specific fields you are trying to retrieve for your collection)
- [ ] add a new Github user to the Arctos Users team
- [ ] a new barcode series
- [ ] a new term for data entry or management 
- [ ] a change or new report or label
- [ ] update to an Agent (split, merge, or other type of change)
- [ ] bulkload changes (to Agents, Identifiers, etc that are not already available as a bulkloading tool)
- [ ] new feature or otherwise a good idea to make Arctos even better
- [ ] quarantine taxon name and suggested replacement (please supply links)
- [ ] other

**Describe what you're trying to do** 
the Object Tracking working group proposes removing the "Container: Add Parts" tool because it can only add single parts to single containers. Checking with @campmlc @falco-rk @LitsaWoo @asemerdj @megulbranson @DerekSikes @amgunderson @cjconroy to see if anyone uses this tool.

**Comment by dustymc** [comment]
This is a duplicate of https://github.com/ArctosDB/arctos/issues/8220
